### ISSUE TITLE
Branch cannot be found

### ISSUE THREAD

**Issue by hanhan23333** [CZB666-wdnmd/kernelsu_xiaomi_equuleus_action#2]
I git clone https://github.com/CZB666-wdnmd/android_kernel_xiaomi_sdm845.git -b udc-kernelsu --depth=1 kernel_sdm845 in line 25 of your main.yaml, in https://github.com/ CZB666-wdnmd/android_kernel_xiaomi_sdm845 This warehouse does not have the udc-kernelsu branch, which makes it impossible to continue. I changed the verification of the last step of Patch kernel source to other branches under the same project and the problem occurred many times. I would like to ask how to solve it.

**Comment by CZB666-wdnmd** [comment]
Please switch branches and build it yourself. In addition, I have almost given up maintaining this project, and kernelsu officially no longer supports non-gki kernel.
